version: '3'
services:
    nginx:
        image: nginx:latest
        platform: linux/amd64 
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/
        depends_on:
            - php
        networks:
            - app-network

    php:
        build: ./docker/php
        volumes:
            - ./src:/var/www/
        networks:
            - app-network

    mysql:
        image: mysql:8.0.26
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_pass
        command:
            --default_authentication_plugin=mysql_native_password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=laravel_user
            - PMA_PASSWORD=laravel_pass
        depends_on:
            - mysql
        ports:
            - 8080:80
        networks:
            - app-network

networks:
    app-network:
        driver: bridge