
name: Run PHPUnit Tests with MySQL and phpMyAdmin

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: laravel_user
          MYSQL_PASSWORD: laravel_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
          - 8080:80
        env:
          PMA_HOST: mysql
          PMA_PORT: 3306
        options: --health-cmd="curl --silent --fail http://localhost:80" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite, gd, curl, zip
          coverage: xdebug

      - name: Install dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-interaction --prefer-dist
        working-directory: ./src  # composer.jsonがsrcディレクトリ内にあるため

      - name: Prepare .env file
        run: |
          cp .env.example .env.testing
          echo "DB_CONNECTION=mysql" >> .env.testing
          echo "DB_HOST=mysql" >> .env.testing
          echo "DB_PORT=3306" >> .env.testing
          echo "DB_DATABASE=test_db" >> .env.testing
          echo "DB_USERNAME=laravel_user" >> .env.testing
          echo "DB_PASSWORD=laravel_pass" >> .env.testing
          echo "SESSION_DRIVER=array" >> .env.testing
        working-directory: ./src

      - name: Generate application key
        run: php artisan key:generate --env=testing
        working-directory: ./src  # artisanコマンドをsrcディレクトリ内で実行

      - name: Run migrations
        run: php artisan migrate:fresh --env=testing
        working-directory: ./src  # artisanコマンドをsrcディレクトリ内で実行

      - name: Run tests
        run: php artisan test --env=testing
        working-directory: ./src  # artisanコマンドをsrcディレクトリ内で実行

      - name: Check phpMyAdmin URL
        run: |
          echo "phpMyAdmin is available at http://localhost:8080"