
name: Run PHPUnit Tests with MySQL and phpMyAdmin

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: laravel_user
          MYSQL_PASSWORD: laravel_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite, mysql, pdo_mysql, gd, curl, zip
          coverage: xdebug

      - name: Verify MySQL connection
        run: |
          mysql --host 127.0.0.1 --port 3306 -uroot -proot -e "SHOW DATABASES;"

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist
        working-directory: ./src

      - name: Prepare .env file
        run: |
          cp .env.example .env.testing
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env.testing
          sed -i 's/DB_PORT=.*/DB_PORT=3306/' .env.testing
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=test_db/' .env.testing
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=laravel_user/' .env.testing
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=laravel_pass/' .env.testing
          sed -i 's/SESSION_DRIVER=.*/SESSION_DRIVER=array/' .env.testing
        working-directory: ./src

      - name: Generate application key
        run: php artisan key:generate --env=testing
        working-directory: ./src

      - name: Run migrations
        run: php artisan migrate:fresh --env=testing --force
        working-directory: ./src

      - name: Run tests
        run: php artisan test --env=testing
        working-directory: ./src